### Obtener todos los usuarios (Solo admin)
GET http://localhost:3000/users
x-auth: admin_auth

###

### Registrar nuevo usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Alan Casino",
  "email": "alan@example.com",
  "password": "12345678"
}

###

### Login de usuario (loginUser)
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "alan@example.com",
  "password": "12345678"
}

###

### Obtener un usuario por ID 
GET http://localhost:3000/users/681a7470b73cd1ea8758b285

###

### Actualizar un usuario (PATCH) 
PATCH http://localhost:3000/users/681a7470b73cd1ea8758b285
Content-Type: application/json
x-auth: 12345678

{
  "balance": 1800
}

###

### Eliminar usuario (DELETE) NO BORRAR ES DE PRUEBA SI SIRVE
DELETE http://localhost:3000/users/681a7470b73cd1ea8758b285


